config/routes.rb
Rails.application.routes.draw do

  # Scrum Routes
  # http://guides.rubyonrails.org/routing.html#controller-namespaces-and-routing
  namespace :scrum do
    # Nested Resources: https://stackoverflow.com/a/10661690/1093087
    resources :boards, shallow: true do
      member do
        # Show view tabs.
        get 'sprints', to: 'boards#show'
        get 'chart', to: 'boards#show'
        get 'contributors', to: 'boards#show'
        get 'events', to: 'boards#show'
        get 'imports', to: 'boards#show'
      end

      resources :queues, shallow: true do
        resources :stories, except: [:index]

        member do
          # Show view tabs.
          get 'stories', to: 'queues#show'
          get 'contributors', to: 'queues#show'
          get 'events', to: 'queues#show'
        end
      end

      resources :events
    end

    resources :contributors, only: [:index, :show] do
      member do
        # Show view tabs.
        get 'sprints', to: 'contributors#show'
        get 'stories', to: 'contributors#show'
      end
    end

    post 'board/import', to: 'boards#import'
  end

  # Trello Routes
  namespace :trello do
    resources :boards, only: [:index, :show] do
      collection do
        get 'all', to: 'boards#index'
        get 'scrum', to: 'boards#scrum'
      end
    end

    post 'board/import', to: 'boards#import'
  end
  get '/trello/imports', to: 'trello/imports#index'
  get '/trello/imports/:id', to: 'trello/imports#show', as: 'trello_import'
  patch '/trello/imports/abort/:id', to: 'trello/imports#abort', as: 'trello_import_abort'
  get '/trello/orgs', to: 'trello#orgs_index'
  get '/trello/orgs/:id/boards', to: 'trello#orgs_boards_index', as: 'trello_orgs_boards'

  # Charts Routes
  get '/charts/scrum_board/:id', to: 'charts#scrum_board', as: 'scrum_board_charts'

  # Authentication
  get '/authenticate', to: 'sessions#new', as: :auth_confirm
  get '/auth/:provider/callback', to: 'sessions#create', as: :auth_callback
  get '/sign_out', to: 'sessions#destroy', as: :sign_out
  get '/auth/failure', to: 'sessions#failure'

  # Sidekiq Monitor
  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/controllers/trello/boards_controller.rb
module Trello
  class BoardsController < ApplicationController
    before_action :set_active_boards, only: [:index, :scrum]

    # GET trello/boards/
    def index
      @boards = @boards.sort_by(&:last_activity_date).reverse
    end

    # GET trello/boards/scrum
    def scrum
      @boards = @boards.keep_if { |b| ScrumBoard.scrummy_trello_board?(b) }
      @boards = @boards.sort_by(&:last_activity_date).reverse
      render :index
    end

    # GET trello/board/:id
    def show
      @trello = TrelloService.new
      @trello_board = TrelloService.board(params[:id])
      @scrum_board = ScrumBoard.find_by(trello_board_id: @trello_board.id)
    end

    # POST trello/board/import
    def import
      trello_board_id = params[:id]

      # Existing boards should be updated.
      existing_board = ScrumBoard.find_by(trello_board_id: trello_board_id)
      if existing_board.present?
        return redirect_to scrum_board_path(existing_board), notice: 'Board already exists.'
      end

      # Create import.
      trello_board = TrelloService.board(trello_board_id)
      scrum_board = ScrumBoard.find_or_create_by_trello_board(trello_board)
      import = TrelloImport.create(scrum_board: scrum_board)

      # Hand off to worker.
      TrelloBoardImportWorker.perform_async(import.id)

      # Redirect to imports page
      redirect_to trello_imports_path, notice: 'Import started.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_active_boards
      @trello = TrelloService.new

      # If you don't filter out the boards with nil for last_activity_date, sort_by will
      # choke. Why do some boards have a nil value for this field? ¯\_(ツ)_/¯
      @boards = @trello.public_boards.keep_if { |b| b.last_activity_date.present? }
    end
  end
end

app/controllers/trello/imports_controller.rb
module Trello
  class ImportsController < ApplicationController
    before_action :authenticate
    before_action :auth_scrum_masters
    before_action :set_import, only: [:show, :abort]

    # GET /trello/imports
    # GET /trello/imports.json
    def index
      @imports = TrelloImport.order(created_at: :desc)

      respond_to do |format|
        format.html
        format.json { render json: @imports }
      end
    end

    # GET /trello/imports/1
    # GET /trello/imports/1.json
    def show; end

    # PATCH /trello/imports/abort/1
    def abort
      return redirect_to trello_import_path(@import) unless @import.stuck?
      @import.abort_now
      redirect_to trello_import_path(@import), notice: 'Stuck import aborted.'
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_import
      @import = TrelloImport.find(params[:id])
    end
  end
end

app/controllers/trello_controller.rb
class TrelloController < ApplicationController
  def boards_index
    @trello = TrelloService.new

    # If you don't filter out the boards with nil for last_activity_date, sort_by will
    # choke. Why do some boards have a nil value for this field? ¯\_(ツ)_/¯
    active_boards = @trello.public_boards.keep_if { |b| b.last_activity_date.present? }
    @boards = active_boards.sort_by(&:last_activity_date).reverse
  end

  def orgs_index
    @trello = TrelloService.new
    @orgs = @trello.public_orgs
  end

  def orgs_boards_index
    @org = TrelloService.org(params[:id])
    active_boards = @org.boards.keep_if { |b| b.last_activity_date.present? }
    @boards = active_boards.sort_by(&:last_activity_date).reverse
  end

  # GET trello/boards/:id
  def boards_show
    @trello = TrelloService.new
    @trello_board = TrelloService.board(params[:id])
    @scrum_board = ScrumBoard.find_by(trello_board_id: @trello_board.id)
  end
end

app/views/trello/_boards_table.html.erb
<table class="table table-sm">
  <thead>
    <tr>
      <th scope="col" class="icon"></th>
      <th scope="col">Board</th>
      <th scope="col">ID</th>
      <th scope="col">URL</th>
      <th scope="col">Last Activity</th>
      <th scope="col" class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= trello_board_icon(board) %></td>
        <th scope="row"><%= board.name %></th>
        <th scope="row"><%= board.id %></th>
        <td><%= link_to board.url, board.url %></td>
        <td><%= board.last_activity_date %></td>
        <td>
          <%= link_to show_icon, trello_boards_show_path(board.id) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/trello/boards_show.html.erb
<div class="page-header">
  <h2>Trello Board <span class="text-primary"><%= @trello_board.name %></span></h2>
  <p><%= @trello_board.description %></p>

  <p>
  <% if ScrumBoard.scrummy_trello_board?(@trello_board) && @scrum_board.nil? %>
    <%= form_for ScrumBoard.new, url: scrum_boards_path, method: :post do |f| %>
      <%= f.hidden_field :trello_board_id, value: @trello_board.id %>
      <%= f.submit "Create Project", class: "btn btn-success" %>
    <% end %>
  <% elsif @scrum_board %>
    <a href="<%= scrum_board_path(@scrum_board) %>">
      <%= scrum_icon %>
      <%= @scrum_board.name %>
    </a>
  <% end %>
  </p>
</div>

<dl class="dl-horizontal">
  <dt><strong>URL</strong></dt>
  <dd><%= link_to @trello_board.url, @trello_board.url %></dd>
  <dt><strong>Org</strong></dt>
  <dd><%= board_org_link(@trello_board) %></dd>
</dl>

<%= link_to 'back', trello_boards_path, role: 'button', class: 'btn btn-primary' %>

app/views/trello/orgs_boards_index.html.erb
<h2>Trello Boards</h2>
<p class="lead">For org <%= @org.display_name %><p>
<p><%= @boards.count %> boards listed<p>

<%= render partial: "boards_table" %>

app/views/trello/orgs_index.html.erb
<h2>Trello Organizations</h2>
<p class="lead">For user <%= @trello.me.username %><p>
<p><%= @orgs.count %> orgs listed<p>

<table class="table table-sm">
  <thead>
    <tr>
      <th scope="col">Org</th>
      <th scope="col">URL</th>
      <th scope="col">Boards</th>
    </tr>
  </thead>
  <tbody>
    <% @orgs.each do |org| %>
      <tr>
        <th scope="row"><%= org.display_name %></th>
        <td><%= link_to org.url, org.url %></td>
        <td><%= link_to org.boards.count, trello_orgs_boards_path(org.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>