config/routes.rb
Rails.application.routes.draw do

  # Scrum Routes
  # http://guides.rubyonrails.org/routing.html#controller-namespaces-and-routing
  namespace :scrum do
    # Nested Resources: https://stackoverflow.com/a/10661690/1093087
    resources :boards, shallow: true do
      member do
        # Show view tabs.
        get 'sprints', to: 'boards#show'
        get 'chart', to: 'boards#show'
        get 'contributors', to: 'boards#show'
        get 'events', to: 'boards#show'
        get 'imports', to: 'boards#show'
      end

      resources :queues, shallow: true do
        resources :stories, except: [:index]

        member do
          # Show view tabs.
          get 'stories', to: 'queues#show'
          get 'contributors', to: 'queues#show'
          get 'events', to: 'queues#show'
        end
      end

      resources :events
    end

    resources :contributors, only: [:index, :show] do
      member do
        # Show view tabs.
        get 'sprints', to: 'contributors#show'
        get 'stories', to: 'contributors#show'
      end
    end

    post 'board/import', to: 'boards#import'
  end

  # Trello Routes
  namespace :trello do
    resources :boards, only: [:index, :show] do
      collection do
        get 'all', to: 'boards#index'
        get 'scrum', to: 'boards#scrum'
      end
    end

    post 'board/import', to: 'boards#import'
  end
  get '/trello/imports', to: 'trello/imports#index'
  get '/trello/imports/:id', to: 'trello/imports#show', as: 'trello_import'
  patch '/trello/imports/abort/:id', to: 'trello/imports#abort', as: 'trello_import_abort'
  get '/trello/orgs', to: 'trello#orgs_index'
  get '/trello/orgs/:id/boards', to: 'trello#orgs_boards_index', as: 'trello_orgs_boards'

  # Charts Routes
  get '/charts/scrum_board/:id', to: 'charts#scrum_board', as: 'scrum_board_charts'

  # Authentication
  get '/authenticate', to: 'sessions#new', as: :auth_confirm
  get '/auth/:provider/callback', to: 'sessions#create', as: :auth_callback
  get '/sign_out', to: 'sessions#destroy', as: :sign_out
  get '/auth/failure', to: 'sessions#failure'

  # Sidekiq Monitor
  if Rails.env.development?
    require 'sidekiq/web'
    mount Sidekiq::Web => '/sidekiq'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
end

app/controllers/scrum/boards_controller.rb
module Scrum
  class BoardsController < ApplicationController
    before_action :authenticate
    before_action :auth_scrum_masters, only: [:new, :create, :edit, :update, :destroy]
    before_action :set_scrum_board, only: [:show, :edit, :update, :destroy]
    before_action :set_scrum_board_tab, only: [:show]

    # GET /scrum_boards
    # GET /scrum_boards.json
    def index
      @scrum_boards = ScrumBoard.all
    end

    # GET /scrum/boards/1
    # GET /scrum/boards/1/sprints
    # GET /scrum/boards/1/chart
    # GET /scrum/boards/1/contributors
    # GET /scrum/boards/1/events
    # GET /scrum/boards/1/imports
    def show; end

    # GET /scrum_boards/new
    def new
      @scrum_board = ScrumBoard.new
    end

    # GET /scrum_boards/1/edit
    def edit; end

    # POST /scrum_boards
    # POST /scrum_boards.json
    # rubocop: disable Metrics/AbcSize
    def create
      trello_board_id = scrum_board_params[:trello_board_id]
      trello_board = TrelloService.board(trello_board_id)

      unless trello_board
        redirect_to trello_boards_path, notice: 'Trello backlog not found.'
        return
      end

      @scrum_board = ScrumBoard.by_trello_board_or_create(trello_board)

      respond_to do |format|
        if @scrum_board.save
          format.html { redirect_to @scrum_board, notice: 'Board was successfully created.' }
          format.json { render :show, status: :created, location: @scrum_board }
        else
          format.html { render :new }
          format.json { render json: @scrum_board.errors, status: :unprocessable_entity }
        end
      end
    end
    # rubocop: enable Metrics/AbcSize

    # PATCH/PUT /scrum_boards/1
    # PATCH/PUT /scrum_boards/1.json
    def update
      respond_to do |format|
        if @scrum_board.update(scrum_board_params)
          format.html { redirect_to @scrum_board, notice: 'Backlog was successfully updated.' }
          format.json { render :show, status: :ok, location: @scrum_board }
        else
          format.html { render :edit }
          format.json { render json: @scrum_board.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /scrum/board/1
    # DELETE /scrum/board/1.json
    def destroy
      @scrum_board.destroy
      respond_to do |format|
        format.html {
          redirect_to scrum_boards_url, notice: 'Backlog was successfully destroyed.'
        }
        format.json { head :no_content }
      end
    end

    # POST /scrum/board/import
    # rubocop: disable Metrics/AbcSize
    def import
      board = ScrumBoard.find(scrum_board_params[:id])
      import = TrelloImport.create(scrum_board: board)

      if import.errors.any?
        notice = format('Import failed: %s', import.errors.full_messages.to_sentence)
        return redirect_to scrum_board_path(board), notice: notice
      end

      # Hand off import to worker.
      TrelloBoardImportWorker.perform_async(import.id)

      # Redirect to imports page
      redirect_to trello_import_path(import),
                  notice: "Importing latest events for #{board.name} board."
    end
    # rubocop: enable Metrics/AbcSize

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_scrum_board
      @scrum_board = ScrumBoard.find(params[:id])
    end

    def set_scrum_board_tab
      # Is there a better way to do this? Params doesn't work:
      # GET /scrum/boards/1/sprints -> {"controller"=>"scrum/boards", "action"=>"show", "id"=>"1"}
      valid_tabs = ['sprints', 'chart', 'contributors', 'events', 'imports']
      @tab = request.fullpath.split('/').last
      @tab = valid_tabs.first unless valid_tabs.include? @tab
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scrum_board_params
      params.require(:scrum_board).permit(:id, :trello_board_id, :trello_url, :name,
                                          :last_board_activity_at, :last_imported_at)
    end
  end
end

app/controllers/scrum/contributors_controller.rb
module Scrum
  class ContributorsController < ApplicationController
    before_action :authenticate
    before_action :auth_scrum_masters
    before_action :set_contributor, only: [:show]
    before_action :set_scrum_contributor_tab, only: [:show]

    # GET /scrum/contributors
    # GET /scrum/contributors.json
    def index
      @contributors = ScrumContributor.all.sort_by(&:avg_capacity).reverse

      respond_to do |format|
        format.html
        format.json { render json: @contributors }
      end
    end

    # GET /scrum/contributors/1
    # GET /scrum/contributors/1/sprints
    # GET /scrum/contributors/1/stories
    def show; end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_contributor
      @contributor = ScrumContributor.find(params[:id])
    end

    def set_scrum_contributor_tab
      valid_tabs = ['sprints', 'stories']
      @tab = request.fullpath.split('/').last
      @tab = valid_tabs.first unless valid_tabs.include? @tab
    end
  end
end

app/controllers/scrum/events_controller.rb
module Scrum
  class EventsController < ApplicationController
    before_action :authenticate
    before_action :set_event, only: [:show]

    # GET /scrum/events/1
    # GET /scrum/events/1.json
    def show; end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = ScrumEvent.find(params[:id])
    end
  end
end

app/controllers/scrum/projects_controller.rb
module Scrum
  class ProjectsController < ApplicationController
    before_action :set_scrum_project, only: [:show, :edit, :update, :destroy]

    # GET /scrum_projects
    # GET /scrum_projects.json
    def index
      @scrum_projects = ScrumProject.all
    end

    # GET /scrum_projects/1
    # GET /scrum_projects/1.json
    def show; end

    # GET /scrum_projects/new
    def new
      @scrum_project = ScrumProject.new
    end

    # GET /scrum_projects/1/edit
    def edit; end

    # POST /scrum_projects
    # POST /scrum_projects.json
    def create
      @scrum_project = ScrumProject.new(scrum_project_params)

      respond_to do |format|
        if @scrum_project.save
          format.html {
            redirect_to @scrum_project,
                        notice: 'Scrum project was successfully created.'
          }
          format.json { render :show, status: :created, location: @scrum_project }
        else
          format.html { render :new }
          format.json { render json: @scrum_project.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /scrum_projects/1
    # PATCH/PUT /scrum_projects/1.json
    def update
      respond_to do |format|
        if @scrum_project.update(scrum_project_params)
          format.html {
            redirect_to @scrum_project,
                        notice: 'Scrum project was successfully updated.'
          }
          format.json { render :show, status: :ok, location: @scrum_project }
        else
          format.html { render :edit }
          format.json { render json: @scrum_project.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /scrum_projects/1
    # DELETE /scrum_projects/1.json
    def destroy
      @scrum_project.destroy
      respond_to do |format|
        format.html {
          redirect_to scrum_projects_url,
                      notice: 'Scrum project was successfully destroyed.'
        }
        format.json { head :no_content }
      end
    end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_scrum_project
      @scrum_project = ScrumProject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scrum_project_params
      params.require(:scrum_project).permit(:name)
    end
  end
end

app/controllers/scrum/queues_controller.rb
module Scrum
  class QueuesController < ApplicationController
    before_action :authenticate
    before_action :auth_scrum_masters, only: [:new, :create, :edit, :update]
    before_action :set_queue, only: [:edit, :update, :show]
    before_action :set_scrum_queue_tab, only: [:show]

    # GET /scrum/sprints
    # GET /scrum/sprints.json
    def index
      @scrum_sprints = ScrumSprint.all
    end

    # GET /scrum/boards/:board_id/sprints/new
    def new
      @scrum_sprint = ScrumSprint.new
      @scrum_sprint.scrum_board = ScrumBoard.find(params[:board_id])
    end

    # POST /scrum/boards/:board_id/sprints
    # rubocop: disable Metrics/AbcSize
    def create
      @scrum_sprint = ScrumSprint.create(scrum_sprint_params)

      respond_to do |format|
        if @scrum_sprint.save
          format.html {
            redirect_to ScrumBoard.find(params[:board_id]),
                        notice: 'Sprint was successfully created.'
          }
          format.json { render :show, status: :created, location: @scrum_sprint }
        else
          format.html { render :new }
          format.json { render json: @scrum_sprint.errors, status: :unprocessable_entity }
        end
      end
    end
    # rubocop: enable Metrics/AbcSize

    # GET /scrum/sprints/:id/edit
    def edit; end

    # PATCH/PUT /scrum/sprints/:id
    # PATCH/PUT /scrum_boards/:id.json
    def update
      respond_to do |format|
        if @scrum_sprint.update(scrum_sprint_params)
          format.html {
            redirect_to @scrum_sprint.board, notice: 'Sprint was successfully updated.'
          }
          format.json { render :show, status: :ok, location: @scrum_sprint }
        else
          format.html { render :edit }
          format.json { render json: @scrum_sprint.errors, status: :unprocessable_entity }
        end
      end
    end

    # GET /scrum/queues/1
    # GET /scrum/queues/1/stories
    # GET /scrum/queues/1/contributors
    # GET /scrum/queues/1/events
    def show; end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_queue
      @queue = ScrumQueue.find(params[:id])
    end

    def set_scrum_queue_tab
      valid_tabs = ['stories', 'contributors', 'events']
      @tab = request.fullpath.split('/').last
      @tab = valid_tabs.first unless valid_tabs.include? @tab
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scrum_sprint_params
      params.require(:scrum_sprint).permit(
        :scrum_board_id, :name, :started_on, :ended_on, :notes
      )
    end
  end
end

app/controllers/scrum/stories_controller.rb
module Scrum
  class StoriesController < ApplicationController
    before_action :authenticate
    before_action :set_story, only: [:show]

    # GET /scrum/user_stories/1
    # GET /scrum/user_stories/1.json
    def show; end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_story
      @story = ScrumStory.find(params[:id])
    end
  end
end

app/controllers/scrum/user_stories_controller.rb
module Scrum
  class UserStoriesController < ApplicationController
    before_action :authenticate
    before_action :set_user_story, only: [:show]

    # GET /scrum/user_stories/1
    # GET /scrum/user_stories/1.json
    def show; end

    private

    # Use callbacks to share common setup or constraints between actions.
    def set_user_story
      @user_story = UserStory.find(params[:id])
    end
  end
end

app/helpers/scrum/boards_helper.rb
module Scrum::BoardsHelper
  def trello_url_link(scrum_board, opts={})
    alt = opts.fetch('alt', 'Not Available')

    if scrum_board.trello_url
      link_to scrum_board.trello_url, scrum_board.trello_url
    else
      tag.span alt, class: 'text-muted'
    end
  end

  def scrum_board_nav_tab_class(tab_label)
    tab_label = tab_label.downcase
    @tab == tab_label ? 'active' : 'inactive'
  end
end

app/helpers/scrum/contributors_helper.rb
module Scrum::ContributorsHelper
  def contributor_avatar(contributor, **options)
    size = options[:size] || 32
    avatar_class = format('avatar r%s', size)

    return '' if contributor.avatar_url.nil?
    image_tag contributor.avatar_url, class: avatar_class
  end
end

app/helpers/scrum/queues_helper.rb
module Scrum::QueuesHelper
  def scrum_sprint_form_url(queue)
    if queue.new_record?
      scrum_board_queues_path(queue.scrum_board, queue)
    else
      queue
    end
  end

  def import_completed_sprint_button(sprint)
    return '' unless sprint.over?
    link_to import_icon, import_queue_path(sprint), remote: true, data: { type: :html },
                                                    class: 'import-sprint'
  end
end

app/views/scrum/queues/_table.html.erb
<table class="sprints table table-sm">
  <thead>
    <tr>
      <th scope="col">Name</th>
      <th scope="col">Start</th>
      <th scope="col">End</th>
      <th scope="col">Completed</th>
      <th scope="col"><%= ScrumBoard::NUM_SPRINTS_FOR_AVG_VELOCITY %>-Sprint Avg Velocity</th>
      <th scope="col">Avg Story Size</th>
      <th scope="col">Backlog</th>
      <th scope="col">Wish Heap</th>
      <th scope="col">Notes</th>
      <th scope="col" class="actions"></th>

    </tr>
  </thead>
  <tbody>
    <%= render partial: 'scrum/queues/table_row', collection: queues, as: :queue %>
  </tbody>
</table>

app/views/scrum/queues/_table_row.html.erb
<tr>
  <th scope="row"><%= queue.name %></th>
  <td><%= queue.started_on %></td>
  <td><%= queue.ended_on %></td>
  <td class="story_points_completed"><%= queue.points %></td>
  <td class="average_velocity"><%= queue.average_velocity %></td>
  <td class="average_story_size"><%= queue.average_story_size %></td>
  <td class="backlog_story_points"><%= queue.backlog_points %></td>
  <td class="wish_heap_story_points"><%= queue.wish_heap_points %></td>
  <td class="actions">
    <%= link_to show_icon, queue %>
  </td>
</tr>

app/views/scrum/queues/show.html.erb
<div class="page-header">
  <h2>Sprint <span class="text-primary"><%= @queue.date_name %></span></h2>
  <p><%#= link_to 'Edit', edit_scrum_sprint_path(@scrum_sprint), role: 'button', class: 'btn btn-primary' %></p>
</div>

<div class="row">
  <div class="col-sm">
    <dl class="dl-horizontal">
      <dt><strong>Started</strong></dt>
      <dd><%= @queue.started_on %></dd>
      <dt><strong><%= @queue.over? ? 'Ended' : 'Ends' %></strong></dt>
      <dd><%= @queue.ended_on %></dd>
      <dt><strong>Last Trello Pull</strong></dt>
      <dd><%= @queue.events.last.created_at %></dd>
      <dt><strong>Notes</strong></dt>
      <dd><%= @queue.notes || '(no notes)' %></dd>
    </dl>
  </div>
  <div class="col-sm">
    <%# TODO: Button to pull info from Trello %>
    <h4><span class="badge badge-pill badge-light">
      <%= 'N/A' %></span> Story Points Committed
    </h4>
    <h4><span class="badge badge-pill badge-success">
      <%= @queue.points %></span> Story Points Completed
    </h4>
    <% unless @queue.active_sprint? %>
      <h4><span class="badge badge-pill badge-info">
        <%= @queue.average_velocity %></span>
        <%= ScrumBoard::NUM_SPRINTS_FOR_AVG_VELOCITY %>-Sprint Avg Velocity
      </h4>
    <% end %>
    <h4><span class="badge badge-pill badge-info">
      <%= @queue.average_story_size %></span> Average Story Size
    </h4>
  </div>
</div>

<!-- Previous/Next Buttons -->
<div class="adjacent-nav pb-2 clearfix">
  <% if @queue.previous.present? %>
    <div class="float-left">
      <%= link_to("&laquo; Sprint #{@queue.previous.date_name}".html_safe,
                  @queue.previous,
                  class: 'btn btn-light') %>
    </div>
  <% end %>

  <% if @queue.next.present? %>
    <div class="float-right">
      <%= link_to("Sprint #{@queue.next.date_name} &raquo;".html_safe,
                  @queue.next,
                  class: 'btn btn-light')  %>
    </div>
  <% end %>
</div>

<!-- Nav Tabs -->
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link <%= scrum_board_nav_tab_class('Stories') %>"
      href="<%= stories_scrum_queue_path(@queue) %>">Stories</a>
  </li>
  <li class="nav-item">
    <a class="nav-link <%= scrum_board_nav_tab_class('Contributors') %>"
       href="<%= contributors_scrum_queue_path(@queue) %>">Contributors</a>
  </li>
  <li class="nav-item">
    <a class="nav-link <%= scrum_board_nav_tab_class('Events') %>"
       href="<%= events_scrum_queue_path(@queue) %>">Events</a>
  </li>
</ul>

<% if @tab == 'contributors' %>
  <%= render partial: "scrum/sprint_contributions/table",
             locals: {contributions: @queue.sprint_contributions} %>
<% elsif @tab == 'events' %>
  <%= render partial: "scrum/events/board_table", locals: {events: @queue.events} %>
<% else %>
  <%= render partial: "scrum/stories/table", locals: {stories: @queue.groomed_stories} %>
<% end %>

<div class="actions">
  <%= link_to 'Scrum Board', scrum_board_path(@queue.scrum_board), role: 'button', class: 'btn btn-info ml-2' %>
</div>